### ISSUE TITLE
OutputStreamWrappingHttpServletResponse does not extend HttpServletResponseWrapper

### ISSUE THREAD

**Issue by jfrommann** [miltonio/milton2#106]
When using miltons's ModelAndView to render a JSP homepage it works totally fine in Tomcat. But when the application is run by Wildfly this exception occurs:

```
java.lang.IllegalArgumentException: UT010024: Response io.milton.servlet.OutputStreamWrappingHttpServletResponse@526faa7e was not original or a wrapper
        at io.undertow.servlet.spec.RequestDispatcherImpl.includeImpl(RequestDispatcherImpl.java:324)
        at io.undertow.servlet.spec.RequestDispatcherImpl.setupIncludeImpl(RequestDispatcherImpl.java:311)
        at io.undertow.servlet.spec.RequestDispatcherImpl.include(RequestDispatcherImpl.java:277)
        at io.milton.http.template.JspViewResolver$JspTemplateProcessor.execute(JspViewResolver.java:96)
        at io.milton.http.annotated.GetAnnotationHandler.processTemplate(GetAnnotationHandler.java:120)
        at io.milton.http.annotated.GetAnnotationHandler.execute(GetAnnotationHandler.java:91)
        ... 49 more
```

The solution for this is that OutputStreamWrappingHttpServletResponse must extend HttpServletResponseWrapper. I patched milton myself and now the homepage works fine in Wildfly. Here is the patched code:

```java
public class OutputStreamWrappingHttpServletResponse extends HttpServletResponseWrapper {

    private final HttpServletResponse response;
    private final OutputStream out;
    private final PrintWriter writer;

    public OutputStreamWrappingHttpServletResponse(HttpServletResponse response, OutputStream out) {
        super(response);
        this.response = response;
        this.out = out;
        writer = new PrintWriter(out);
    }

    @Override
    public String encodeUrl(String url) {
        return MiltonServlet.response().encodeURL(url);
    }

    @Override
    public String encodeRedirectUrl(String url) {
        return MiltonServlet.response().encodeRedirectURL(url);
    }

    @Override
    public void sendRedirect(String location) throws IOException {
        MiltonServlet.response().sendRedirect(location);
    }

    @Override
    public ServletOutputStream getOutputStream() throws IOException {
        return new WrappedOutputStream();
    }

    @Override
    public PrintWriter getWriter() throws IOException {
        return writer;
    }

    @Override
    public void flushBuffer() throws IOException {
        writer.flush();
        out.flush();
        response.flushBuffer();
    }

    @Override
    public void setLocale(Locale loc) {
        MiltonServlet.response().setLocale(loc);
    }

    @Override
    public Locale getLocale() {
        return MiltonServlet.response().getLocale();
    }

    private class WrappedOutputStream extends ServletOutputStream {

        @Override
        public void write(int b) throws IOException {
            out.write(b);
        }

        @Override
        public void write(byte[] b) throws IOException {
            out.write(b);
        }

        @Override
        public void write(byte[] b, int off, int len) throws IOException {
            out.write(b, off, len);
        }
    }
}
```

**Comment by bradmac** [comment]
Thanks for the patch, thats been applied.
