### ISSUE TITLE
Failed to read license xml

### ISSUE THREAD

**Issue by svieujot** [miltonio/milton2#140]
Works with version `2.8.0.1` but with `2.8.0.2`, I get:
```
INFO  2020 Sep 19, 15:55:46 [main] io - Initializing Milton2 Webdav library Enterprise edition. . Local milton version: 2.8.0.2
WARN  2020 Sep 19, 15:55:46 [main] io - Exception checking for milton commercial license: io.milton.webdav.exceptions.ServerException: Failed to read license xml. If you have a commercial license please check with the licensor at http://milton.io

[Fatal Error] :1:1: Content is not allowed in prolog.
io.milton.webdav.exceptions.ServerException: Failed to read license xml.
	at io.milton.webdav.license.LicenseValidator.checkLicense(Unknown Source)
	at io.milton.webdav.utils.LockUtils.getValidatedLicenseProperties(Unknown Source)
	at io.milton.webdav.utils.LockUtils.displayCopyrightNotice(Unknown Source)
	at io.milton.webdav.utils.LockUtils.<clinit>(Unknown Source)
	at io.milton.http.webdav2.LockHandler.<init>(LockHandler.java:43)
	at io.milton.http.webdav2.WebDavLevel2Protocol.<init>(WebDavLevel2Protocol.java:51)
	at io.milton.ent.config.HttpManagerBuilderEnt.buildProtocolHandlers(HttpManagerBuilderEnt.java:209)
	at io.milton.config.HttpManagerBuilder.initProtocols(HttpManagerBuilder.java:519)
	at io.milton.config.HttpManagerBuilder.init(HttpManagerBuilder.java:488)
	at io.milton.config.HttpManagerBuilder.init(HttpManagerBuilder.java:405)
	at io.milton.config.HttpManagerBuilder.buildHttpManager(HttpManagerBuilder.java:530)
	at io.milton.servlet.DefaultMiltonConfigurator.build(DefaultMiltonConfigurator.java:174)
	at io.milton.servlet.DefaultMiltonConfigurator.configure(DefaultMiltonConfigurator.java:156)
	at io.milton.servlet.MiltonFilter.init(MiltonFilter.java:69)
	at com.seanergie.webdav.servlet.WebDavFilter.init(WebDavFilter.java:25)
	at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:270)
	at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:251)
	at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:102)
	at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4528)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5165)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909)
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:843)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909)
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:421)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.startup.Tomcat.start(Tomcat.java:486)
	at com.seanergie.web.embedded.WebappLauncher.run(WebappLauncher.java:74)
	at com.equitativa.intranet.Main.main(Main.java:8)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:128)
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at java.xml/com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:261)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
	at java.xml/javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:122)
	... 49 more
```

The `milton.license.properties` and `milton.license.sig` are located at the root of one of our jar files.
I get the same error if I move the license files at the root of the webapp.

**Comment by ophiuhus** [comment]
Thank you for your question. You are right, the new license is required to activate v2.8.02+. To use the versions 2.8.0.2+, please log-in to the product download area here: https://milton.io/downloads/ with the email that was specified during the purchase and download the new license. Please note that you may need to reset your password.
