### ISSUE TITLE
NPE during handling MKCOL request which finishes with '/'

### ISSUE THREAD

**Issue by tkleszczynski** [miltonio/milton2#33]
Hello,

A NPE is thrown from io.milton.http.webdav.MkColHandler.process, line 85 upon request for creating directory / file with name '/'.

Following is the stack trace:

15:01:52.291 INFO  io.milton.http.HttpManager - MKCOL :: http://127.0.0.1:8081/abc%20-%207f6f50e8-904e-4b33-9c18-fde8e86c4f1f// start
15:01:52.311 ERROR io.milton.http.StandardFilter - exception sending content
java.lang.NullPointerException: null
    at io.milton.http.webdav.MkColHandler.process(MkColHandler.java:85) ~[milton-server-ce-2.6.2.2.jar:na]
    at io.milton.http.webdav.MkColHandler.process(MkColHandler.java:65) ~[milton-server-ce-2.6.2.2.jar:na]
    at io.milton.http.StandardFilter.process(StandardFilter.java:51) ~[milton-server-ce-2.6.2.2.jar:na]
    at io.milton.http.FilterChain.process(FilterChain.java:40) [milton-server-ce-2.6.2.2.jar:na]
    at io.milton.http.HttpManager.process(HttpManager.java:153) [milton-server-ce-2.6.2.2.jar:na]
    at io.milton.servlet.MiltonServlet.service(MiltonServlet.java:127) [milton-server-ce-2.6.2.2.jar:na]
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:594) [org.eclipse.jetty.aggregate.jetty-all-server_8.1.0.v20120127.jar:8.1.0.v20120127]
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:485) [org.eclipse.jetty.aggregate.jetty-all-server_8.1.0.v20120127.jar:8.1.0.v20120127]
    at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:69) [org.ops4j.pax.web.pax-web-jetty_3.1.1.jar:na]
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119) [org.eclipse.jetty.aggregate.jetty-all-server_8.1.0.v20120127.jar:8.1.0.v20120127]
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:521) [org.eclipse.jetty.aggregate.jetty-all-server_8.1.0.v20120127.jar:8.1.0.v20120127]
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:233) [org.eclipse.jetty.aggregate.jetty-all-server_8.1.0.v20120127.jar:8.1.0.v20120127]
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1065) [org.eclipse.jetty.aggregate.jetty-all-server_8.1.0.v20120127.jar:8.1.0.v20120127]
    at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:240) [org.ops4j.pax.web.pax-web-jetty_3.1.1.jar:na]
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:412) [org.eclipse.jetty.aggregate.jetty-all-server_8.1.0.v20120127.jar:8.1.0.v20120127]
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:192) [org.eclipse.jetty.aggregate.jetty-all-server_8.1.0.v20120127.jar:8.1.0.v20120127]
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:999) [org.eclipse.jetty.aggregate.jetty-all-server_8.1.0.v20120127.jar:8.1.0.v20120127]
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117) [org.eclipse.jetty.aggregate.jetty-all-server_8.1.0.v20120127.jar:8.1.0.v20120127]
    at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:77) [org.ops4j.pax.web.pax-web-jetty_3.1.1.jar:na]
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111) [org.eclipse.jetty.aggregate.jetty-all-server_8.1.0.v20120127.jar:8.1.0.v20120127]
    at org.eclipse.jetty.server.Server.handle(Server.java:351) [org.eclipse.jetty.aggregate.jetty-all-server_8.1.0.v20120127.jar:8.1.0.v20120127]
    at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:451) [org.eclipse.jetty.aggregate.jetty-all-server_8.1.0.v20120127.jar:8.1.0.v20120127]
    at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:916) [org.eclipse.jetty.aggregate.jetty-all-server_8.1.0.v20120127.jar:8.1.0.v20120127]
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:634) [org.eclipse.jetty.aggregate.jetty-all-server_8.1.0.v20120127.jar:8.1.0.v20120127]
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:230) [org.eclipse.jetty.aggregate.jetty-all-server_8.1.0.v20120127.jar:8.1.0.v20120127]
    at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:76) [org.eclipse.jetty.aggregate.jetty-all-server_8.1.0.v20120127.jar:8.1.0.v20120127]
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:609) [org.eclipse.jetty.aggregate.jetty-all-server_8.1.0.v20120127.jar:8.1.0.v20120127]
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:45) [org.eclipse.jetty.aggregate.jetty-all-server_8.1.0.v20120127.jar:8.1.0.v20120127]
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:599) [org.eclipse.jetty.aggregate.jetty-all-server_8.1.0.v20120127.jar:8.1.0.v20120127]
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:534) [org.eclipse.jetty.aggregate.jetty-all-server_8.1.0.v20120127.jar:8.1.0.v20120127]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_20]
15:01:52.311 WARN  io.milton.servlet.ServletResponse - sendError: HTTP/1.1 500
15:01:52.311 INFO  io.milton.servlet.ServletResponse - Closed outputstream after sendError
15:01:52.311 INFO  io.milton.http.HttpManager - MKCOL :: http://127.0.0.1:8081/abc%20-%207f6f50e8-904e-4b33-9c18-fde8e86c4f1f// finished 20ms, Status:null, Length:null

**Comment by bradmac** [comment]
Closing old issue. Please reopen if you would like assistance.
